ekolokwium/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from kolokwium import views as kolokwium_views

urlpatterns = [
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^kolokwium/', include('kolokwium.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', kolokwium_views.index, name='index'),
]

kolokwium/urls.py
from django.conf.urls import url

from . import views

app_name = 'kolokwium'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<kolokwium_id>[0-9]+)/$', views.kolokwium, name='kolokwium'),
    url(r'^(?P<kolokwium_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.question, name='question'),
    url(r'^(?P<kolokwium_id>[0-9]+)/(?P<question_id>[0-9]+)/answer/$', views.answer, name='answer'),
]

kolokwium/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class Kolokwium(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    kolokwium = models.ForeignKey(Kolokwium, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    
    def __str__(self):
        return self.choice_text
    
class UserAnswer(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class ValidChoice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

kolokwium/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from .models import *

def index(request):
    return render(request, 'kolokwium/index.html', {'kolokwium_list': Kolokwium.objects.all()})

def kolokwium(request, kolokwium_id):
    kolokwium = get_object_or_404(Kolokwium, pk=kolokwium_id)
    questions_and_answers = None
    if request.user.is_authenticated:
        questions_and_answers = []
        questions = Question.objects.filter(kolokwium=kolokwium)
        for q in questions:
            answer = UserAnswer.objects.filter(user=request.user, choice__question=q)
            if len(answer) == 0:
                questions_and_answers.append((q, None))
            else:
                answer = answer[0]
                valid = ValidChoice.objects.filter(question=q, choice=answer.choice)
                if len(valid) == 0:
                    questions_and_answers.append((q, False))
                else:
                    questions_and_answers.append((q, True))
    return render(request, 'kolokwium/kolokwium.html', {'kolokwium': kolokwium, 'questions_and_answers': questions_and_answers})

def question(request, kolokwium_id, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answers = UserAnswer.objects.filter(choice__question=question)
    answer = None
    good = None
    if request.user.is_authenticated and len(answers) > 0:
        answer = answers[0]
        good = ValidChoice.objects.filter(question=question)[0].choice
    return render(request, 'kolokwium/question.html', {'question': question, "answer": answer, "good": good})


@login_required
def answer(request, kolokwium_id, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'kolokwium/question.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        answer = UserAnswer()
        answer.choice = selected_choice
        answer.user = request.user
        answer.save()
        return HttpResponseRedirect(reverse('kolokwium:question', args=(kolokwium_id, question.id)))

kolokwium/templates/index.html
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}  <a href="{% url 'logout' %}">[logout]</a></p>
{% else %}
    <p>Welcome, Guest <a href="{% url 'login' %}">[login]</a></p>
{% endif %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

kolokwium/templates/kolokwium/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<div id="login_header">
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}  <a href="{% url 'logout' %}">[logout]</a></p>
{% else %}
    <p>Welcome, Guest <a href="{% url 'login' %}">[login]</a></p>
{% endif %}
</div>
<div id="content">
{% block content %}
{% endblock %} 
</div>

kolokwium/templates/kolokwium/index.html
{% extends 'kolokwium/base.html' %}
{% block content %}

    <h1>Kolokwia</h1><hr>
    
    <div id="inner-content">

    {% if kolokwium_list %}
        <table>
        {% for kolokwium in kolokwium_list %}
            <tr><td><a href="{% url 'kolokwium:kolokwium' kolokwium.id %}">{{ kolokwium.name }}</a><tr><td>
        {% endfor %}
        </table>
    {% else %}
        <p>No kolokwiums are available.</p>
    {% endif %}
    
     </div>
    
{% endblock %}

kolokwium/templates/kolokwium/kolokwium.html
{% extends 'kolokwium/base.html' %}
{% block content %}

    
    <div class="back"><a href="{% url 'kolokwium:index' %}">&larr; Do listy kolokwiów</a></div>

    <h1>{{ kolokwium.name }}</h1><hr>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div id="inner-content">
    <table>
    {% if questions_and_answers %}
        <th>Question</th><th>Answer</th>
        {% for q in questions_and_answers %}
            <tr>
                <td><a href="{% url 'kolokwium:question' kolokwium.id q.0.id %}">{{ q.0.question_text }}</a></td>
                {%if q.1 == True%}
                    <td class="answer"><div class="answer-ok">OK</div></td>
                {% elif q.1 == False %}
                    <td class="answer"><div class="answer-ans">ANS</div></td>
                {% else %}
                    <td class="answer"><div class="answer-none">NONE</div></td>
                {% endif %}
            </tr>
        {% endfor %}
    {% else %}
        {% for question in kolokwium.question_set.all %}
            <tr><td><a href="{% url 'kolokwium:question' kolokwium.id question.id %}">{{ question.question_text }}</a></td></tr>
        {% endfor %}
    {% endif %}
    </table>
    </div>
    
{% endblock %}

kolokwium/templates/kolokwium/question.html
{% extends 'kolokwium/base.html' %}
{% block content %}

    <div class="back"><a href="{% url 'kolokwium:kolokwium' question.kolokwium.id %}">&larr; Do listy pytań</a></div>

    <h1>{{ question.question_text }}</h1><hr>
    
    <div id="inner-content">

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    {% if answer %}
        <table>
        {% for choice in question.choice_set.all %}
        {% if choice == good %}
            <tr><td class="choice-good">{{ choice.choice_text }}</td></tr>
        {% elif choice == answer.choice and choice != good %}
            <tr><td class="choice-bad">{{ choice.choice_text }}</td></tr>
        {% else %}
            <tr><td>{{ choice.choice_text }}</td></tr>
        {% endif %}
        {% endfor %}
        </table>
    {% else %}

        <form action="{% url 'kolokwium:answer' question.kolokwium.id question.id %}" method="post">
        {% csrf_token %}
        <table>
        {% for choice in question.choice_set.all %}
            <tr><td><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label></td></tr>
        {% endfor %}
        </table><br>
        <input class="answer-btn" type="submit" value="Answer" />
        </form>
        
    </div>
    
    {% endif %}
{% endblock %}